### PR TITLE
NoPrimary for reco

### PR DESCRIPTION
**Pull request by brownd1978**
Configure NoPrimary so the output can be run through (sim) reconstruction.  Note that Offline PR 608 is a prequiste for this PR.

### CODE REVIEW

**Comment by soleti** [comment]
There are some conflicts to be resolved. @brownd1978 is there a reason why you deleted all the examples? Were they outdated?

**Comment by kutschke** [comment]
This PR has a lot of cleanup changes that are duplicates with PR #102 so it took me a while to sort through it.  I think that the following 5 files are the real intellectual content of this PR when it is applied after 102.  I describe below how I got there

M       JobConfig/digitize/prolog.fcl
M       JobConfig/mixing/Mix.fcl
M       JobConfig/mixing/NoPrimary.fcl
A       JobConfig/mixing/epilog.fcl
M       JobConfig/mixing/prolog.fcl

Dave: does that look right?

I added Roberto as a reviewer because I think that some of the follow-up to Roberto's comments on PR #102 might have ended up in this PR.   But I am not sure.  Certainly files were changed in both and they are not always the same changes: for example MDC2020/gen_OffSpill.sh , MDC2020/gen_OnSpill.sh , JobConfig/primary/prolog.fcl, JobConfig/beam/prolog.fcl  

To help understand this I did a few things.  First, I did test merges onto main first in the order 102 then 106.  And then in the reverse order.  In the order 106 followed by 102 I had to resolve 2 conflicts by hand which I resolved by taking the file from nullprimary with no changes.  The conflicts were in JobConfig/beam/prolog.fcl and  JobConfig/primary/prolog.fcl .

The two merge orders produce identical results.  This surprised me a little since there are files that were modified in both so I expected the two merge orders to produce different results.

In case either of you are interested in looking at the final result, I have put the two merges on my fork of Production:
https://github.com/kutschke/Production/tree/mergeIndentNull
https://github.com/kutschke/Production/tree/mergeNullIndent

Finally I did: 
git checkout mergeIndentNull
git diff  --name-status ec44da02   # This is the sha of the merge commit for the merge of indent.

M       JobConfig/digitize/prolog.fcl
M       JobConfig/mixing/Mix.fcl
M       JobConfig/mixing/NoPrimary.fcl
A       JobConfig/mixing/epilog.fcl
M       JobConfig/mixing/prolog.fcl

I believe that these 5 files are the real intellectual content of this PR.

**Comment by brownd1978** [comment]
The deleted files in this PR were all outdated (MDC2018 era) and either have already been replaced or will be replaced soon.

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Review by soleti — APPROVED** [review]

**Pull request merged**
