### PR TITLE
Use split target stop types

### PR DESCRIPTION
**Pull request by brownd1978**

### CODE REVIEW

**Comment by kutschke** [comment]
@soleti Hi Roberto.  Welcome back.  I just want to make sure that the request to review this PR is in your queue.

**Review by soleti — APPROVED** [review]

**Comment by soleti** [comment]
@kutschke thanks for the reminder, I just approved it.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by kutschke** [comment]
@brownd1978 Dave, does this PR need to be coordinated with anything or can it be merged at any time?

**Pull request merged**
