### PR TITLE
Speeding up G4 cosmic resampling

### PR DESCRIPTION
**Pull request by soleti**
Upon @oksuzian suggestion I added few lines to `S2Resampler.fcl` which give a factor of ~2 speedup. However, I am not exactly sure of what these modifications are actually doing, @oksuzian could you please say a bit more? Thanks.

### CODE REVIEW

**Review by oksuzian — COMMENTED** [review]
We need to check that the impact on physics is minimal by introducing these cuts.
I will simulate a small CRY sample with and without these cuts to estimate the reconstruction efficiencies.

**Review by resnegfk — CHANGES_REQUESTED** [review]
The placement of the g4run.physics changes does not seem to be correct,
if JobConfig/cosmic/S2Resampler.fcl is to be the main inpu fcl file,
as some of the params are overwritten in the Production/JobConfig/primary/epilog.fcl

resulting in:
            minRangeRegionCuts: {
               CalorimeterMother: 1e-1
            }
            noDecay: []
            physicsListName: "ShieldingM_EMZ"

Perhaps one should create another epilog for that stage?

Other than that the choice of the intended parameters seems to be reasonable,
if one want to have a detailed simulation in the tracker, but not elsewhere.
It would seem one should use SheildingM_EMZ in stages involving DS/tracker only.
The:
physics.producers.g4run.physics.physicsListName: ShieldingM
physics.producers.g4run.physics.useEmOption4InTracker: true
is close to that, and seem appropriate for cosmic simulations.

**Comment by soleti** [comment]
Thank you for your comment @resnegfk, you're right those settings are overwritten by the epilog. @oksuzian can you make sure your test files have the correct settings? Once we confirm there are no significant changes in the outcome I will modify this PR and include a dedicated epilog.

**Comment by soleti** [comment]
I moved the settings to a dedicated epilog. @oksuzian verified that the two versions (with and without these settings) agree at the 0.1% level.

**Review by oksuzian — APPROVED** [review]
These are the settings we've tested.
It improves the resampling stage by about 50% without a visible impact on physics.

**Review by resnegfk — APPROVED** [review]
Apart from the lack of the new line in JobConfig/cosmic/resampling_epilog.fcl
(would the style checker flag that? :) )
it seems fine now

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
Please fix the missing newline in resampling_epilog.fcl

**Pull request merged**
