### PR TITLE
Add PV info and consolidate/simplify playload specification

### PR DESCRIPTION
**Pull request by brownd1978**
This PR addresses a problem that Ed noticed in working on filtering IPA DIO, that the pileup streams are missing the PhysicalVolumeInfo (PVI) objects. This wasn't seen until now as we don't run further G4 stages on these collections, and nothing prior to this in our workflows depended on the PVI. It is needed here (and for target DIO) when combining generic pileup with dedicated tall simulations to avoid double-counting when making ensembles.

### CODE REVIEW

**Comment by brownd1978** [comment]
This is draft because I haven't yet tested all the affected scripts.

**Comment by brownd1978** [comment]
Tests finished. The PVInfo payload is now visible in the dts outputs:
PRINCIPAL TYPE: SubRun
PROCESS NAME... | MODULE LABEL......... | PRODUCT INSTANCE NAME | DATA PRODUCT TYPE...................................... | PRODUCT FRIENDLY TYPE...... | SIZE
MuBeamResampler | compressPVTargetStops | ..................... | std::vector<cet::map_vector<mu2e::PhysicalVolumeInfo> > | mu2e::PhysicalVolumeInfomvs | ...2
MuBeamResampler | compressPVIPAStops... | ..................... | std::vector<cet::map_vector<mu2e::PhysicalVolumeInfo> > | mu2e::PhysicalVolumeInfomvs | ...2
MuBeamResampler | genCounter........... | ..................... | mu2e::GenEventCount.................................... | mu2e::GenEventCount........ | ...-

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by edcallaghan** [comment]
Looks good to me. Thanks Dave.

**Review by edcallaghan — APPROVED** [review]

**Pull request merged**
