### PR TITLE
Removed gen_MuFlatDaughter.sh

### PR DESCRIPTION
**Pull request by sophiemiddleton**
Issue https://github.com/Mu2e/Production/issues/208 asked for this script to be removed. Additional tests needed

### CODE REVIEW

**Comment by sophiemiddleton** [comment]
(this PR builds on top of [my other PR](https://github.com/Mu2e/Production/pull/212))

**Review by brownd1978 — APPROVED** [review]
This PR sholud be merged after 212

**Comment by sophiemiddleton** [comment]
I missed a file, will push it now

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Pull request merged**
