### PR TITLE
fixed trigger config

### PR DESCRIPTION
**Pull request by gianipez**
The file was tested locally with the NoPrimary1BB sample

### CODE REVIEW

**Comment by kutschke** [comment]
I  updated my working area and ran the nightly jobs locally.   The trigger job is running and is up to 1025 events so I believe that's likely to be resolved.

This PR does not fix the crash in the nightly ceMix job  - did you expect it to?
What's the next step?

This will reproduce the crash in ceMix in less than 30 seconds of running time:

   mu2e -c Production/Validation/nightly/ceMix_10.fcl 

it uses xrootd so you need to run vomsCert  (https://mu2ewiki.fnal.gov/wiki/DataTransfer#xrootd)

**Comment by gianipez** [comment]
Hi Rob,

When I run it locally I see this error:
20-Feb-2024 09:50:28 CST  Initiating request to open input file "root://fndcadoor.fnal.gov/pnfs/fnal.gov/usr/mu2e/tape/phy-sim/dts/mu2e/CePlusEndpoint/MDC2020r/art/be/db/dts.mu2e.CePlusEndpoint.MDC2020r.001210_00000089.art"
%MSG-s ArtException:  ***@***.***  20-Feb-2024 09:50:31 CST ModuleConstruction
cet::exception caught in art
---- FileOpenError BEGIN
  ---- FatalRootError BEGIN
    Fatal Root Error: TNetXNGFile::Open
    [FATAL] Auth failed: No protocols left to try
    ROOT severity: 3000
  ---- FatalRootError END
  
  RootInputFileSequence::initFile(): Input file root://fndcadoor.fnal.gov/pnfs/fnal.gov/usr/mu2e/tape/phy-sim/dts/mu2e/CePlusEndpoint/MDC2020r/art/be/db/dts.mu2e.CePlusEndpoint.MDC2020r.001210_00000089.art was not found or could not be opened.
---- FileOpenError END
%MSG
Art has completed and will exit with status 20.

which I don’t think is related to the trigger reconstruction. Am I missing anything?

Gianantonio Pezzullo, Ph.D. (he/him/his)
***@***.***


**********************************************************************************************************
Address: Department of Physics, Yale University, 56 Hillhouse, New Haven, CT-06511, USA
Phone   : ‭+1 (331) 205-9306‬  	     		
**********************************************************************************************************

**Comment by kutschke** [comment]
The jobs use xrootd so you need to run vomsCert (https://mu2ewiki.fnal.gov/wiki/DataTransfer#xrootd)

From: Gianantonio Pezzullo ***@***.***>
Reply-To: Mu2e/Production ***@***.***>
Date: Tuesday, February 20, 2024 at 9:53 AM
To: Mu2e/Production ***@***.***>
Cc: Rob Kutschke ***@***.***>, Team mention ***@***.***>
Subject: Re: [Mu2e/Production] fixed trigger config (PR #296)


[EXTERNAL] – This message is from an external sender
Hi Rob,

When I run it locally I see this error:
20-Feb-2024 09:50:28 CST Initiating request to open input file "root://fndcadoor.fnal.gov/pnfs/fnal.gov/usr/mu2e/tape/phy-sim/dts/mu2e/CePlusEndpoint/MDC2020r/art/be/db/dts.mu2e.CePlusEndpoint.MDC2020r.001210_00000089.art"
%MSG-s ArtException: ***@***.*** 20-Feb-2024 09:50:31 CST ModuleConstruction
cet::exception caught in art
---- FileOpenError BEGIN
---- FatalRootError BEGIN
Fatal Root Error: TNetXNGFile::Open
[FATAL] Auth failed: No protocols left to try
ROOT severity: 3000
---- FatalRootError END

RootInputFileSequence::initFile(): Input file root://fndcadoor.fnal.gov/pnfs/fnal.gov/usr/mu2e/tape/phy-sim/dts/mu2e/CePlusEndpoint/MDC2020r/art/be/db/dts.mu2e.CePlusEndpoint.MDC2020r.001210_00000089.art was not found or could not be opened.
---- FileOpenError END
%MSG
Art has completed and will exit with status 20.

which I don’t think is related to the trigger reconstruction. Am I missing anything?

Gianantonio Pezzullo, Ph.D. (he/him/his)
***@***.***


**********************************************************************************************************
Address: Department of Physics, Yale University, 56 Hillhouse, New Haven, CT-06511, USA
Phone : +1 (331) 205-9306
**********************************************************************************************************

**Review by kutschke — APPROVED** [review]
I made a local clone to test.  This PR plus mu2e_trig_config PR 3 fix the crashes in validation that occurred on the morning of Feb 20, 2024.

**Pull request merged**
