### PR TITLE
Script updates

### PR DESCRIPTION
**Pull request by sophiemiddleton**
Some new scripts examples of use of GetOpts for more user control

### CODE REVIEW

**Review by kutschke — COMMENTED** [review]
I am curious about the introduction of the Old subdirectory.  Are you doing this just for archival purposes or do you expect that you might need to use these again? 

For example is generate_POT.sh the successor to Old/gen_POT.sh?

**Review by brownd1978 — COMMENTED** [review]
If the gen_Digitize is no longer needed it should be removed, not just put in Old, as git will remember it.  If it is still needed it shouldn't be moved to Old.  Was the change from Digitize to Digitization intentional?

**Comment by sophiemiddleton** [comment]
Old is just there because I'm still testing things, it will be removed once all the .cfg scripts are updated to use the new scripts. I just wanted review on these first before moving to the full transition, also I cant do that until we get the deg field study finished

**Comment by kutschke** [comment]
> Old is just there because I'm still testing things, it will be removed once all the .cfg scripts are updated to use the new scripts. I just wanted review on these first before moving to the full transition, also I cant do that until we get the deg field study finished

Thanks - I will approve it now. Be sure to remember to remove it when you are done.

**Review by kutschke — APPROVED** [review]

**Review by brownd1978 — APPROVED** [review]

**Pull request merged**
