### PR TITLE
Redistribute and encapsulate payload definitions

### PR DESCRIPTION
**Pull request by brownd1978**
Also add some scripts to strip out MC information.
This redistribution removes some redundancies and allows clearer choices of payload content going forwards.

### CODE REVIEW

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Review by rlcee — APPROVED** [review]
Without digging into details, this look very reasonable.  I see your FNALbuild command didn't work.  I can see in the log that it didn't match the regex, but I can't see why.

**Comment by kutschke** [comment]
@oksuzian a gentle reminder that this PR is on your list to review

@brownd1978 the issue on ceSimReco is renaming MCRecoProducts to HighMCRecoProducts .  A followup change is needed in Production/Validation/ceSimReco.fcl

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@rlcee, I should add that I tested that the payload of ceSimReco is 'identical' before and after this change.

**Comment by kutschke** [comment]
@oksuzian a gentle reminder that this is on your list of PRs to review

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Comment by brownd1978** [comment]
@FNALbuild run build test

**Pull request merged**
