### PR TITLE
Adapt to separation of BField config from Geometry config

### PR DESCRIPTION
**Pull request by kutschke**
This is needed for Offline PR #765.  See also the conversation for that PR.

Find all references to geom_common_reco.txt and replace with
   services.GeometryService.inputFile      : "Offline/Mu2eG4/geom/geom_common.txt"
   services.GeometryService.bFieldFile     : "Offline/Mu2eG4/geom/bfgeom_reco_v01.txt"

When this process converges we will remove geom_common_reco.txt

### CODE REVIEW

**Comment by kutschke** [comment]
These failures were expected.  This is being retested in Offline PR 765.

**Review by AndrewEdmonds11 — APPROVED** [review]
Looks good to me!

**Review by soleti — APPROVED** [review]

**Comment by brownd1978** [comment]
Let me know if its not clear how to merge the changes from 168 into this PR.

**Comment by kutschke** [comment]
> Let me know if its not clear how to merge the changes from 168 into this PR.

It looks straightforward.  I am looking at it now.

**Comment by kutschke** [comment]
The conflicts created by the merge of #168 have been fixed.   That merge also created a new point of maintenance, JobConfig/digitize/epilog.fcl ; that's fixed too.

@FNALbuild run build test with Mu2e/Offline#765

**Review by rlcee — APPROVED** [review]
It is a little disconcerting to see a geom file replaced by a bfield file, but I think this has the intended effect due to the nature of the geom file, and I'm sure you have checked this point.

**Comment by kutschke** [comment]
> It is a little disconcerting to see a geom file replaced by a bfield file, but I think this has the intended effect due to the nature of the geom file, and I'm sure you have checked this point.

It looked weird to me at first as well.

In cases where the geometry file override existed only to override the BField, the default geometry file (geom_common) is correct and does not need to be overridden.  In some of the changes added today the geometry file override changes both geometry and bfield - so both are present in the new version.  See, for example, JobConfig/common/epilog_muplus_DS50_reco.fcl

**Comment by kutschke** [comment]
@FNALbuild run build test with Mu2e/Offline#765

**Pull request merged**
