### PR TITLE
use DB for CRV digitization

### PR DESCRIPTION
**Pull request by ehrlich-uva**
Sets useDB true for two CRV modules.
Merge needs to wait until Offline PR 1163 has been merged, and the DB tables have been added.

### CODE REVIEW

**Comment by kutschke** [comment]
@ehrlich-uva Does this need to be tested with the current head of Offline or is it waiting for additional updaes?

**Comment by ehrlich-uva** [comment]
@kutschke This PR can only be tested after PR 1163 has been merged into Offline and the two database tables (the ones I mentioned in my email) have been added. This Production PR turns on the use of these tables for the CRV digitization.

**Comment by kutschke** [comment]
@ehrlich-uva Ok.  I will wait for the database table work to complete before rerunning CI.  To remind you we request that the the CI run by taking the head of Production + this PR and the head of Offline plus a list of Offline PRs.  But there is no point in doing that until the database work is complete.

Is it possible and reasonable to separate the database work from these two PRs and do it in a separate PR?

**Comment by ehrlich-uva** [comment]
@kutschke Activating the use of the database is the only thing that happens in this Production PR. The database work is a major part of Offline PR 1163 and would be difficult to separate. Also, Offline PR 1163 will still work without this Production PR - without it, the validation jobs will use the nominal scintillation yields without fluctuations and no dead channels.

**Comment by kutschke** [comment]
Thanks @ehrlich-uva I understand now and will wait for the work in Offline to finiish.

**Comment by kutschke** [comment]
@FNALbuild run build test with Mu2e/Offline#1163

**Comment by ehrlich-uva** [comment]
The reason why these tests failed is because this Production PR enabled the database usage for CRVPhotonYield and CRVStatus without providing the tables - either via DbService.textFile or the "real" database. I could add them temporarily via DbService.textFile to see, if the tests pass before we make a decision on how to handle the database issue.

**Comment by kutschke** [comment]
> The reason why these tests failed is because this Production PR enabled the database usage for CRVPhotonYield and CRVStatus without providing the tables - either via DbService.textFile or the "real" database. I could add them temporarily via DbService.textFile to see, if the tests pass before we make a decision on how to handle the database issue.

Tomorrow at the the meeting we can discuss how to proceed.

**Comment by kutschke** [comment]
@FNALbuild run build test

**Comment by ehrlich-uva** [comment]
This PR can be merged, after the following files from Offline PR 1201 have been added to the database and Offline PR 1201 has been merged.
CRVConditions/data/calib_nominal.txt
CRVConditions/data/photonyield_nominal.txt
CRVConditions/data/status_nominal.txt

**Review by brownd1978 — APPROVED** [review]
This is good for now.

**Comment by brownd1978** [comment]
I believe this fails validation as the database doesn't yet include these proditions.  To proceed we need to:
- upload the relevant tables:
-  create a new version of the 'best' prodition
- update Validation/database.fcl to reference that.  It should be an update to this PR
After ALL those steps the CI and validation should succeed

**Comment by ehrlich-uva** [comment]
This PR is not needed anymore. Its purpose was to turn the DB tables on for the CRV, but this happens now in Offline as a default setting.

**Pull request closed without merging**
