### PR TITLE
Consolidate

### PR DESCRIPTION
**Pull request by brownd1978**
Consolidate some reco config.

### CODE REVIEW

**Comment by kutschke** [comment]
@FNALbulid run build test

**Comment by brownd1978** [comment]
@FNALbulid run build test

**Comment by brownd1978** [comment]
This PR seems stuck.  The originally proposed reviewer didn't respond.  Since it is mostly bug fixes it can be self-approved if necessary.

**Comment by kutschke** [comment]
> This PR seems stuck. The originally proposed reviewer didn't respond. Since it is mostly bug fixes it can be self-approved if necessary.

I had a quick l look am willing to approve and merge today.  Launching CI now

@FNALbuild run build test

**Comment by kutschke** [comment]
@FNALbuild run build test

**Pull request merged**
