### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by brownd1978**
Add TriggerInfo back to the payload.  Fix output stream name for Extracted, and don't include cosmic epilog (Extracted has no S2)

### CODE REVIEW

**Review by sophiemiddleton — APPROVED** [review]

**Comment by brownd1978** [comment]
This is essentially a bug fix PR, it would be good to merge it soon

**Comment by brownd1978** [comment]
[gianipez] was added for informational purposes

**Comment by kutschke** [comment]
> [gianipez] was added for informational purposes

Got it.  I will run the CI now and merge later this evening.  It's bridge night.

@FNALbuiild run build test

**Review by gianipez — APPROVED** [review]

**Comment by kutschke** [comment]
@FNALbuild run build test

Spell it correctly

**Pull request merged**
