### PR TITLE
changed names of included prolog namespaces from the offline

### PR DESCRIPTION
**Pull request by gianipez**

### CODE REVIEW

**Comment by gianipez** [comment]
This PR depends from https://github.com/Mu2e/Offline/pull/1286

**Comment by kutschke** [comment]
> This PR depends from [Mu2e/Offline#1286](https://github.com/Mu2e/Offline/pull/1286)

Does this mean that you need to use "test with" to run the CI?

**Comment by gianipez** [comment]
> > This PR depends from [Mu2e/Offline#1286](https://github.com/Mu2e/Offline/pull/1286)
> 
> Does this mean that you need to use "test with" to run the CI?

Yes please. I forgot how to run that command.

**Comment by kutschke** [comment]
> > > This PR depends from [Mu2e/Offline#1286](https://github.com/Mu2e/Offline/pull/1286)
> > 
> > 
> > Does this mean that you need to use "test with" to run the CI?
> 
> Yes please. I forgot how to run that command.

See https://mu2ewiki.fnal.gov/wiki/GitHubWorkflow#GitHub_Pull_Request_Procedures_and_FNALbuild

@FNALbuild run build test with Mu2e/Offline#1286

**Comment by kutschke** [comment]
And the AL9 build machines are about 4x faster than the SL7 ones.

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Offline/pull/1286 and https://github.com/Mu2e/mu2e_trig_config/pull/31

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Offline/pull/1286 , https://github.com/Mu2e/mu2e_trig_config/pull/31

**Comment by kutschke** [comment]
> @FNALbuild run build test with Mu2e/Offline#1286, Mu2e/mu2e_trig_config#31

We have not added any code to support test with for mu2e_trig_config.  I don't expect it to  work but I could be wrong.  We tried it once before it failed.  But we later learned that there were other problems occuring at the same time so it's possible we did not have a clean test.

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Offline/pull/1286

**Comment by gianipez** [comment]
@FNALbuild run build test with https://github.com/Mu2e/Offline/pull/1286

**Comment by gianipez** [comment]
All the errors left are because the tests are not including https://github.com/Mu2e/mu2e_trig_config/pull/31
I'm waiting for @brownd1978 for merging it w/o creating conflicts with https://github.com/Mu2e/mu2e_trig_config/pull/27

**Review by brownd1978 — APPROVED** [review]
Beyond scope of this PR, we have to better separate the MC-truth matching part of the reco sequence from the pure reco sequence.

**Review by kutschke — APPROVED** [review]
After the merging mu2e_trig_config PR 31, I launched the CI using test with this PR  from Offline PR#1286 .  It passed

**Pull request merged**
